import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Risk Disclosure // Futurist",
  description:
    "Prediction-market trading involves substantial risk. Futurist is a data-analytics platform and does not provide investment advice.",
};

/**
 * Risk Disclosure — the most legally important page on the site. Written to
 * be accurate for what Futurist actually is: a data aggregator + analytics
 * front-end. NOT a broker, NOT registered with any financial regulator, and
 * NOT a source of investment advice.
 *
 * This is a DRAFT for a lawyer to review before charging money. It is not a
 * substitute for legal counsel.
 */
export default function RiskDisclosurePage() {
  return (
    <main className="flex-1 flex flex-col min-h-[calc(100vh-56px)]">
      <article className="max-w-3xl mx-auto w-full px-6 py-10 text-[14px] leading-relaxed text-[var(--fg-dim)]">
        <header className="mb-8">
          <div className="font-mono text-[10px] tracking-[0.2em] text-[var(--fg-mute)] mb-2">
            LEGAL
          </div>
          <h1 className="text-[28px] font-semibold text-[var(--fg)] tracking-tight">
            Risk Disclosure
          </h1>
          <p className="text-[12px] text-[var(--fg-mute)] mt-2 font-mono">
            Last updated: 2026-06-29
          </p>
        </header>

        <Section title="Read this before trading">
          <p>
            Prediction-market trading involves substantial risk of financial
            loss. You can lose all of the funds you commit to any single
            position. Futurist is a data-analytics platform. It does not
            execute trades, hold customer funds, or make investment
            recommendations. Nothing on Futurist is a solicitation to buy or
            sell any security, contract, or other financial instrument.
          </p>
        </Section>

        <Section title="No investment advice">
          <p>
            All content on Futurist — including market prices, order flow,
            price history charts, AI-generated overviews, correlation
            matrices, news headlines, and every other data view — is provided
            for informational purposes only. It is not investment advice,
            financial advice, trading advice, legal advice, or tax advice.
          </p>
          <p>
            Futurist is not registered with the U.S. Securities and Exchange
            Commission (SEC), the Commodity Futures Trading Commission
            (CFTC), the Financial Industry Regulatory Authority (FINRA), or
            any other financial regulator in any jurisdiction. We are not
            broker-dealers, investment advisors, futures commission
            merchants, or introducing brokers.
          </p>
          <p>
            You should consult a licensed financial advisor and, where
            applicable, a licensed attorney and tax professional before
            making any trading decision.
          </p>
        </Section>

        <Section title="Data sourced from third parties">
          <p>
            All market data displayed on Futurist is sourced from third-party
            platforms — currently Kalshi and Polymarket — via their public
            APIs. We do not guarantee the accuracy, completeness, timeliness,
            or continued availability of that data. Prices you see on
            Futurist may be delayed, incorrect, or inconsistent with what is
            displayed on the source platforms.
          </p>
          <p>
            Before placing any trade, verify prices directly on the venue you
            plan to trade on. Futurist is not liable for any loss arising
            from stale, inaccurate, or unavailable data.
          </p>
        </Section>

        <Section title="AI Overview disclaimer">
          <p>
            The AI Overview feature is generated by a large language model
            (currently Google Gemini) using publicly available news
            headlines and general knowledge. Language models can produce
            confident-sounding statements that are inaccurate, out of date,
            or fabricated. Do not treat the AI Overview as fact and do not
            base a trading decision on it without independent verification.
          </p>
        </Section>

        <Section title="Past performance">
          <p>
            Historical price data, correlation coefficients, and backfill
            statistics on Futurist reflect past outcomes only. Past
            performance is not indicative of future results. Correlations
            change. Markets that appear mispriced can stay mispriced longer
            than you can stay solvent.
          </p>
        </Section>

        <Section title="Regulatory & jurisdictional risk">
          <p>
            Prediction-market platforms are regulated differently — or not at
            all — in different jurisdictions. Some prediction markets are
            legally restricted or prohibited entirely in the United States
            and elsewhere. It is your responsibility to determine whether
            trading on any specific platform is legal for you. Futurist does
            not provide legal advice on this question.
          </p>
        </Section>

        <Section title="Availability & service">
          <p>
            Futurist is provided on an "as is" and "as available" basis. We
            make no warranties about continuous availability, uptime, or
            freedom from bugs. Data feeds can fail, be rate-limited, or
            return incorrect responses without notice.
          </p>
        </Section>

        <Section title="Not for minors">
          <p>
            You must be at least 18 years of age (or the legal age of
            majority in your jurisdiction, whichever is higher) to use
            Futurist.
          </p>
        </Section>

        <Section title="Contact">
          <p>
            Questions about this disclosure or the platform generally can be
            sent to the operator via the address listed on the future
            /contact page. This page will be updated when contact
            infrastructure is in place.
          </p>
        </Section>

        <p className="mt-10 font-mono text-[10px] tracking-[0.14em] text-[var(--fg-mute)]">
          This document is a plain-English draft. It is not legal advice and
          does not constitute a legal contract. Have counsel review before
          relying on it commercially.
        </p>
      </article>
    </main>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="mb-8">
      <h2 className="font-mono text-[11px] tracking-[0.18em] uppercase text-[var(--accent-primary)] mb-3">
        {title}
      </h2>
      <div className="space-y-3">{children}</div>
    </section>
  );
}
